[package]
name = "raytracing_weekend"
version = "0.1.0"
authors = ["julien"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
fastrand = "1.4.1"
rayon = "1.5.0"
